### ISSUE TITLE
Crashes server when breaking proxy

### ISSUE THREAD

**Issue by yujukitten** [CyclopsMC/CapabilityProxy#11]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug
- :snail: Performance issue

____
#### Short description:
Several times I have broken proxies just fine but a few times It crashes the entire server

#### Expected behaviour:
Removal of the block

#### Actual behaviour:
Block remains ( 4 times out of 5 ) upon server restart and crash recurs when trying to break it.

#### Steps to reproduce the problem:

1. Proxy attached to Tinkers tank Drain  or Proxy attached to empowerer from actually additions 
2. Have it function with liquid or item going through
3. break Proxy
4... Crash

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: CapabilityProxy-1.12.2-2.0.0.jar
- CyclopsCore: CyclopsCore-1.12.2-0.10.24
- Minecraft: 12.2
- Forge: 14.23.1.2560

#### Log file:

Start of crash file : 

Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at org.cyclops.capabilityproxy.tileentity.TileCapabilityProxy.getFacing(TileCapabilityProxy.java:23)
	at org.cyclops.capabilityproxy.tileentity.TileCapabilityProxy.getTargetPos(TileCapabilityProxy.java:31)
	at org.cyclops.capabilityproxy.tileentity.TileCapabilityProxy.getTarget(TileCapabilityProxy.java:36)
	at org.cyclops.capabilityproxy.tileentity.TileCapabilityProxy.hasCapability(TileCapabilityProxy.java:45)
	at levelup2.skills.crafting.FurnaceEfficiencyBonus.lambda$doFurnaceTicks$0(FurnaceEfficiencyBonus.java:119)

[crash-2017-12-21_01.19.26-server.txt](https://github.com/CyclopsMC/CapabilityProxy/files/1579361/crash-2017-12-21_01.19.26-server.txt)

**Comment by rubensworks** [comment]
Fixed in ff6b35edebc075ae503a0db3fa4447a8fc25beaf
