### ISSUE TITLE
Crash when wrenching

### ISSUE THREAD

**Issue by Timeslice42** [CyclopsMC/CapabilityProxy#3]
Got this crash when accidentally wrenching a c-proxy from pointing at its intended target to pointing at an export tunnel part. I instantly regretted my actions.
[2017-10-03-4.log.gz](https://github.com/CyclopsMC/CapabilityProxy/files/1355859/2017-10-03-4.log.gz)

Technically it looks more like the tunnel exploded than the c-proxy, but since you own both projects...

FYI the world did load fine after a full client shutdown/restart, but I didn't do any further testing with the setup since that's not what I wanted the c-proxy to point at to begin with.

**Comment by rubensworks** [comment]
Note to self:
```
java.lang.NullPointerException: Exception in server tick loop
        at org.cyclops.integratedtunnels.core.TunnelItemHelpers.moveItemsSingle(TunnelItemHelpers.java:113)
        at org.cyclops.integratedtunnels.core.TunnelItemHelpers.moveItemsSingle(TunnelItemHelpers.java:139)
        at org.cyclops.integratedtunnels.core.TunnelItemHelpers.moveItemsStateOptimized(TunnelItemHelpers.java:273)
```

The proper removal code was probably not being called on the tunnel part, will look into it.
